# Generated by Django 5.1.4 on 2025-01-26 06:27

import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_personalinformation_caste_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinformation",
            name="special_condition",
        ),
        migrations.RenameField(
            model_name="personalinformation",
            old_name="diploma_institution_name",
            new_name="research_college_name",
        ),
        migrations.RenameField(
            model_name="personalinformation",
            old_name="diploma_percentage",
            new_name="research_percentage",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="diploma_field",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="is_distance_learning",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="is_first_graduate",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="received_scholarship",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="state",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="twelfth_field",
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="funding",
            field=models.CharField(
                blank=True,
                choices=[("Aided", "Aided"), ("Self-Financed", "Self-Financed")],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=events.models.PersonalInformation.getFileName,
            ),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="research_degree",
            field=models.CharField(
                blank=True,
                choices=[("M.Phil.", "M.Phil."), ("Ph.D.", "Ph.D.")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="research_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Physics", "Physics"),
                    ("Zoology", "Zoology"),
                    ("Mathematics", "Mathematics"),
                    ("Information Technology", "Information Technology"),
                    ("Environmental Sciences", "Environmental Sciences"),
                    ("Biotechnology", "Biotechnology"),
                    ("Computer Science", "Computer Science"),
                    ("Management", "Management"),
                    ("Chemistry", "Chemistry"),
                    ("Tamil", "Tamil"),
                    ("English", "English"),
                    ("Economics", "Economics"),
                    ("History", "History"),
                    ("Commerce", "Commerce"),
                    ("Social Work", "Social Work"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="roll_number",
            field=models.IntegerField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="state_of_residence",
            field=models.CharField(
                choices=[
                    ("Andhra Pradesh", "Andhra Pradesh"),
                    ("Arunachal Pradesh", "Arunachal Pradesh"),
                    ("Assam", "Assam"),
                    ("Bihar", "Bihar"),
                    ("Chhattisgarh", "Chhattisgarh"),
                    ("Goa", "Goa"),
                    ("Gujarat", "Gujarat"),
                    ("Haryana", "Haryana"),
                    ("Himachal Pradesh", "Himachal Pradesh"),
                    ("Jharkhand", "Jharkhand"),
                    ("Karnataka", "Karnataka"),
                    ("Kerala", "Kerala"),
                    ("Madhya Pradesh", "Madhya Pradesh"),
                    ("Maharashtra", "Maharashtra"),
                    ("Manipur", "Manipur"),
                    ("Meghalaya", "Meghalaya"),
                    ("Mizoram", "Mizoram"),
                    ("Nagaland", "Nagaland"),
                    ("Odisha", "Odisha"),
                    ("Punjab", "Punjab"),
                    ("Rajasthan", "Rajasthan"),
                    ("Sikkim", "Sikkim"),
                    ("Tamil Nadu", "Tamil Nadu"),
                    ("Telangana", "Telangana"),
                    ("Tripura", "Tripura"),
                    ("Uttar Pradesh", "Uttar Pradesh"),
                    ("Uttarakhand", "Uttarakhand"),
                    ("West Bengal", "West Bengal"),
                    ("Andaman and Nicobar Islands", "Andaman and Nicobar Islands"),
                    ("Chandigarh", "Chandigarh"),
                    (
                        "Dadra and Nagar Haveli and Daman and Diu",
                        "Dadra and Nagar Haveli and Daman and Diu",
                    ),
                    ("Delhi", "Delhi"),
                    ("Jammu and Kashmir", "Jammu and Kashmir"),
                    ("Ladakh", "Ladakh"),
                    ("Lakshadweep", "Lakshadweep"),
                    ("Puducherry", "Puducherry"),
                    ("Other", "Other"),
                ],
                default="Tamil Nadu",
                max_length=52,
            ),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_information",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="annual_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="caste",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("MBC", "Most Backward Class (MBC)"),
                    ("OBC", "Other Backward Class (OBC)"),
                    ("SC", "Scheduled Caste (SC)"),
                    ("ST", "Scheduled Tribe (ST)"),
                    ("SEBC", "Socially and Educationally Backward Class (SEBC)"),
                    ("EWS", "Economically Weaker Section (EWS)"),
                    ("NT", "Nomadic Tribes"),
                    ("VJ", "Vimukta Jati"),
                    ("Minorities", "Minorities"),
                ],
                default="General",
                max_length=52,
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="current_qualification",
            field=models.CharField(
                choices=[
                    ("10", "10"),
                    ("12", "12"),
                    ("UG", "UG"),
                    ("PG", "PG"),
                    ("Mphil/Ph.D", "Mphil/Ph.D"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="father_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="father_occupation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Other",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="mother_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="mother_occupation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="nationality",
            field=models.CharField(
                choices=[
                    ("Indian", "Indian"),
                    ("OCI", "Overseas Citizen of India"),
                    ("Foreign", "Foreign National"),
                ],
                default="Indian",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="pg_branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Physics", "Physics"),
                    ("Zoology", "Zoology"),
                    ("Mathematics", "Mathematics"),
                    ("Information Technology", "Information Technology"),
                    ("Environmental Sciences", "Environmental Sciences"),
                    ("Data Science", "Data Science"),
                    ("Bioinformatics", "Integrated Bioinformatics"),
                    ("Biotechnology", "Biotechnology"),
                    ("Computer Science", "Computer Science"),
                    ("Actuarial Science", "Actuarial Science"),
                    ("Management", "Management"),
                    ("Chemistry", "Chemistry"),
                    ("Tamil", "Tamil"),
                    ("English", "English"),
                    ("Economics", "Economics"),
                    ("History", "History"),
                    ("Commerce", "Commerce"),
                    ("Social Work", "Social Work"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="pg_degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M.Sc.", "M.Sc."),
                    ("M.A.", "M.A."),
                    ("M.B.A.", "M.B.A."),
                    ("M.Com.", "M.Com."),
                    ("MSW", "Master of Social Work (MSW)"),
                    ("PGDC", "Post-Graduate Diploma in Counselling"),
                    ("DCFCD", "Diploma in Child Focused Community Development"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="phone_number",
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Buddhist", "Buddhist"),
                    ("Christian", "Christian"),
                    ("Hindu", "Hindu"),
                    ("Jain", "Jain"),
                    ("Muslim", "Muslim"),
                    ("Parsi", "Parsi"),
                    ("Sikh", "Sikh"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="ug_branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Physics", "Physics"),
                    ("Zoology", "Zoology"),
                    ("Mathematics", "Mathematics"),
                    ("Information Technology", "Information Technology"),
                    ("Environmental Sciences", "Environmental Sciences"),
                    ("Bioinformatics", "Integrated Bioinformatics"),
                    ("Biotechnology", "Biotechnology"),
                    ("Computer Science", "Computer Science"),
                    (
                        "Actuarial Mathematical Science",
                        "Actuarial Mathematical Science",
                    ),
                    ("Tamil", "Tamil"),
                    ("English", "English"),
                    ("Economics", "Economics"),
                    ("History", "History"),
                    ("Commerce", "Commerce"),
                    (
                        "Commerce (Computer Applications)",
                        "Commerce (Computer Applications)",
                    ),
                    (
                        "Commerce (Professional Accounting)",
                        "Commerce (Professional Accounting)",
                    ),
                    (
                        "Commerce (International Accounting)",
                        "Commerce (International Accounting)",
                    ),
                    ("Commerce (Strategic Finance)", "Commerce (Strategic Finance)"),
                    ("Commerce (FinTech)", "Commerce (FinTech)"),
                    (
                        "Commerce (Business Process Management)",
                        "Commerce (Business Process Management)",
                    ),
                    ("Commerce (Business Analytics)", "Commerce (Business Analytics)"),
                    ("Accounting and Taxation", "Accounting and Taxation"),
                    ("Social Work", "Social Work"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="ug_degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B.Sc.", "B.Sc."),
                    ("B.A.", "B.A."),
                    ("B.B.A.", "B.B.A."),
                    ("B.Com.", "B.Com."),
                    ("B.Voc.", "B.Voc."),
                    ("B.S.W.", "Bachelor of Social Work (BSW)"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="SpecialCondition",
        ),
    ]
