# Generated by Django 5.1.4 on 2025-01-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_personalinformation_special_condition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinformation",
            name="email",
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="roll_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
