# Generated by Django 5.1.4 on 2025-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_personalinformation_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinformation",
            name="tenth_marks",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
