# Generated by Django 5.1.4 on 2025-01-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_personalinformation_tenth_marks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinformation",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
