# Generated by Django 5.1.4 on 2025-01-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_personalinformation_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinformation",
            name="current_qualification",
            field=models.CharField(
                choices=[("UG", "UG"), ("PG", "PG"), ("Mphil/Ph.D", "Mphil/Ph.D")],
                max_length=10,
            ),
        ),
    ]
