# Generated by Django 5.1.4 on 2025-01-26 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_personalinformation_current_qualification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scholarship_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender_certeria",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("All", "All"),
                        ],
                        default="All",
                        max_length=15,
                    ),
                ),
                (
                    "Minimum_Income_certeria",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "Relegion_certeria",
                    models.CharField(
                        choices=[
                            ("Buddhist", "Buddhist"),
                            ("Christian", "Christian"),
                            ("Hindu", "Hindu"),
                            ("Jain", "Jain"),
                            ("Muslim", "Muslim"),
                            ("Parsi", "Parsi"),
                            ("Sikh", "Sikh"),
                            ("All", "All"),
                        ],
                        default="All",
                        max_length=20,
                    ),
                ),
                (
                    "caste_certeria",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("MBC", "Most Backward Class (MBC)"),
                            ("OBC", "Other Backward Class (OBC)"),
                            ("SC", "Scheduled Caste (SC)"),
                            ("ST", "Scheduled Tribe (ST)"),
                            (
                                "SEBC",
                                "Socially and Educationally Backward Class (SEBC)",
                            ),
                            ("EWS", "Economically Weaker Section (EWS)"),
                            ("NT", "Nomadic Tribes"),
                            ("VJ", "Vimukta Jati"),
                            ("Minorities", "Minorities"),
                            ("All", "All"),
                        ],
                        default="All",
                        max_length=52,
                    ),
                ),
                (
                    "minimum_Mark_certeria",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("benifits", models.CharField(max_length=100)),
                ("deadline", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Eligibility_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_notify", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.personalinformation",
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.scholarship_information",
                    ),
                ),
            ],
        ),
    ]
