# Generated by Django 5.1.4 on 2025-01-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_scholarship_information_eligibility_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship_information",
            name="category",
            field=models.CharField(
                choices=[
                    ("State", "State"),
                    ("Central", "Central"),
                    ("Institutional", "Institutional"),
                    ("Private", "Private"),
                ],
                default="State",
                max_length=20,
            ),
        ),
    ]
