# Generated by Django 5.1.4 on 2025-01-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_scholarship_information_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship_information",
            name="funding",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aided", "Aided"),
                    ("Self-Financed", "Self-Financed"),
                    ("All", "All"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
