# Generated by Django 5.1.4 on 2025-01-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_scholarship_information_funding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship_information",
            name="minimum_Mark_certeria",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
