# Generated by Django 5.1.4 on 2025-01-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_alter_scholarship_information_minimum_mark_certeria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinformation",
            name="annual_income",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
