# Generated by Django 5.1.4 on 2025-01-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_alter_personalinformation_annual_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship_information",
            name="qualification",
            field=models.CharField(
                choices=[
                    ("UG", "UG"),
                    ("PG", "PG"),
                    ("Mphil/Ph.D", "Mphil/Ph.D"),
                    ("All", "All"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="caste",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("OBC", "Other Backward Class (OBC)"),
                    ("SC", "Scheduled Caste (SC)"),
                    ("ST", "Scheduled Tribe (ST)"),
                    ("Minorities", "Minorities"),
                ],
                default="General",
                max_length=52,
            ),
        ),
        migrations.AlterField(
            model_name="scholarship_information",
            name="caste_certeria",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("OBC", "Other Backward Class (OBC)"),
                    ("SC", "Scheduled Caste (SC)"),
                    ("ST", "Scheduled Tribe (ST)"),
                    ("Minorities", "Minorities"),
                    ("All", "All"),
                ],
                default="All",
                max_length=52,
            ),
        ),
        migrations.AlterField(
            model_name="scholarship_information",
            name="gender_certeria",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                    ("All", "All"),
                ],
                default="All",
                max_length=15,
            ),
        ),
    ]
