# Generated by Django 5.1.4 on 2025-01-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_scholarship_information_qualification_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scholarship_information",
            old_name="Minimum_Income_certeria",
            new_name="Minimum_Income_criteria",
        ),
        migrations.RenameField(
            model_name="scholarship_information",
            old_name="Relegion_certeria",
            new_name="Relegion_criteria",
        ),
        migrations.RenameField(
            model_name="scholarship_information",
            old_name="caste_certeria",
            new_name="caste_criteria",
        ),
        migrations.RenameField(
            model_name="scholarship_information",
            old_name="gender_certeria",
            new_name="gender_criteria",
        ),
        migrations.RenameField(
            model_name="scholarship_information",
            old_name="minimum_Mark_certeria",
            new_name="minimum_Mark_criteria",
        ),
    ]
